### ISSUE TITLE
camstalker.fun?

### ISSUE THREAD

**Issue by theSoberSobber** [thedmdim/ytstalker#3]
- do you own the camstalker domain too?

**Comment by thedmdim** [comment]
No, this is my friend's one. YtStalker inspired him and he made camstalker

**Comment by theSoberSobber** [comment]
nice! would it be possible to get some contact of your friend? maybe email?

**Comment by thedmdim** [comment]
when i last seen his site there was an email at the bottom

**Comment by theSoberSobber** [comment]
Thanks, I emailed him! I'll close this issue now.

**Comment by theSoberSobber** [comment]
Also is camstalker.fun opensoure too?
